### ISSUE TITLE
Demographics checkbox not media responsive

### ISSUE THREAD

**Issue by ghbuck** [bowdoincollege/Semantigories#6]
Unable to see checks in light mode:

<img width="384" alt="image" src="https://github.com/bowdoincollege/Semantigories/assets/67022940/4edbb6a2-ea54-45f0-a156-22d2420ae7d3">

<img width="380" alt="image" src="https://github.com/bowdoincollege/Semantigories/assets/67022940/f3377525-6c8c-4397-9abd-9a8750fa0b9b">

**Comment by ghbuck** [comment]
The radios also

**Comment by mcccoleman** [comment]
@ghbuck are we strongly opinionated about this or could we instead apply the current dark styling to all users?

**Comment by ghbuck** [comment]
yeah… i am… 😉
